### ISSUE TITLE
Foreword or preface?

### ISSUE THREAD

**Issue by drgrigg** [robinwhittleton/samuel-pepys_the-diary#1]
In the content and ToC landmarks, you've marked the Preface as epub:type="foreword" but shouldn't it be epub:type="preface" ? And in the content the title is given as "Preface" but in the Toc you have it as "Foreword".

**Comment by drgrigg** [comment]
Also in the Toc, you have the landmark item labelled "Introduction" but the actual title of the page is "Particulars of the Life of Samuel Pepys". Am I wrong, do landmark items get given the document division rather than the actual page title?

**Comment by robinwhittleton** [comment]
Regarding the semantics, according to [Z39.98](http://www.daisy.org/z3998/2012/vocab/structure/#h_document-sections) a preface is typically written by the author, a foreward typically written by someone else. So even though it’s titled preface I went for foreword semantics.

For the ToC entries, your `print-toc` tool has worked its wonders in https://github.com/robinwhittleton/samuel-pepys_the-diary/commit/e24a46fb238fe499970448ca76ff54a2b7a1a21e .
