### ISSUE TITLE
Is it worth semanticating italicised graphemes?

### ISSUE THREAD

**Issue by drgrigg** [robinwhittleton/samuel-pepys_the-diary#2]
In searching for unsemanticated `<i>` tags I see that in chapter-111, you have the following:

`“I love my love with an <i>A</i>, because he is so and so: and I hate him with an <i>A</i>`

I've been tagging these kind of things like this:

`“I love my love with an <i epub:type="z3998:grapheme">A</i>, because he is so and so: and I hate him with an <i epub:type="z3998:grapheme">A</i>`

**Comment by robinwhittleton** [comment]
Not a bad idea, but would `z3998:phoneme` be better semantics here?

**Comment by drgrigg** [comment]
Yes, I thought of that afterwards. It's really the spoken word rather than the written one.

**Comment by robinwhittleton** [comment]
Fixed in https://github.com/robinwhittleton/samuel-pepys_the-diary/commit/d21aa526235ec70d4440f0d42b4f1f9a21fba2e5 .
