### ISSUE TITLE
<div> in introduction?

### ISSUE THREAD

**Issue by drgrigg** [robinwhittleton/samuel-pepys_the-diary#3]
I'm not sure why there is a `<div>` in the Introduction, together with associated CSS styling. Is there a particular reason to use a div here rather than a blockquote?

**Comment by robinwhittleton** [comment]
`blockquote` had additional semantics that I didn’t want. It’s purely there to allow a framework for the specific styling to hang off: there’s no hidden semantics in the two-column presentation in the source.
