### ISSUE TITLE
Lint throws up two minor errors

### ISSUE THREAD

**Issue by drgrigg** [robinwhittleton/samuel-pepys_the-diary#4]
> Error: chapter-16.xhtml Illegal white space before noteref.
> 	<a href="endnotes.xhtml#note-1012" id="noteref-1012" epub:type="noteref">1012</a>
> Manual Review: endnotes.xhtml When italicizing language in dialog, italics go INSIDE quotation marks.
> 	”</i>

**Comment by robinwhittleton** [comment]
Yep, that’s a false positive: it’s a quote inside a work title that’s throwing it off. We can treat it as manually reviewed.
