### ISSUE TITLE
Semanticate wants to make changes, some of which may be valid

### ISSUE THREAD

**Issue by drgrigg** [robinwhittleton/samuel-pepys_the-diary#5]
These are all in the endnotes.

In Note 13, you have:

`<abbr>dat. Mar.</abbr>`

Semanticate wants to make this:

`<abbr>dat. <abbr>Mar.</abbr></abbr>` which is clearly wrong. But shouldn't it be:

`<abbr>dat.</abbr> <abbr>Mar.</abbr>`
?

**Comment by drgrigg** [comment]
In note 344, you have:

`<abbr>s. p. s.</abbr>`

Semanticate wants to change this because of the spaces between the letters. 

Should it be:

`<abbr>s.p.s.</abbr>`  ? without the spaces)

or:

`<abbr>s.</abbr> <abbr>p.</abbr> <abbr>s.</abbr>`

?

**Comment by drgrigg** [comment]
In note 1501, you have:

`<abbr>Rt. Hon.</abbr>`

Should this be:

`<abbr>Rt.</abbr> <abbr>Hon.</abbr>`  ?

**Comment by drgrigg** [comment]
In note 2676, semanticate wants to do the following, both of which seem correct:

`Henry <span epub:type="z3998:roman">VIII</span>, died 1557`
and
`<abbr>Mar.</abbr> Paulina, daughter of John Pepys`

**Comment by robinwhittleton** [comment]
I think this is a long-standing misunderstanding of mine regarding how the abbr element works. Fixed in https://github.com/robinwhittleton/samuel-pepys_the-diary/commit/150aa5bcbb0f473ab04ba689e75a1a44a7b2159a . 

The proposed fix to 2676 is incorrect as it’s inside `alt` text :)
